stages:
- build-initrd
- build-srpm
# - build-rpms

build_initrd:
    only:
      -  master@leapp/leapp-actors-internal
    stage: build-initrd
    cache:
        key: "${CI_PIPELINE_ID}"
        paths:
        - sources/dracut/upgrade-boot-files.tgz
    script:
    - 'export BASEDIR="$PWD"'
    - helpers/docker/docker-run.sh
    image: docker-registry.engineering.redhat.com/leapp-builds/leapp-initrd-rhel8-build:latest

build_srpm:
    only:
      -  master@leapp/leapp-actors-internal
    stage: build-srpm
    dependencies:
    - build_initrd
    cache:
        key: "${CI_PIPELINE_ID}"
        paths:
        - sources/dracut/upgrade-boot-files.tgz
    script:
    - dnf install -y git-core make rpm-build copr-cli
    - export LEAPP_INITRD_SKIP=1
    - make srpm
    image: fedora:28
